### ISSUE TITLE
Ambiguities and suggestions for data prep summary statistics

### ISSUE THREAD

**Issue by marcrecurve** [impactlab/caltrack-betatest#12]
Notes after a first pass through the summary stats spec:

Hourly Elec:
- "Number of unique IDs". Which one? SAID? SPID?
- What id is used to define a "user"? SAID? SPID? Or do you need to use xref file?
- How do you define a "missing hour"?
- How do you define an "estimated hour"?
- Where is the "net metering flag"?

Daily gas:
- Is a "user" defined by SPID? Or something else?

Date integration file
- What is "combined project data"?
- What ID for "number of unique IDs in combined project data"? There are a few ID columns
- Why is monthly gas data here? Isn't it being ignored?
- What ID for hourly elec data?
- What ID column in xref?
- How do you define percentage matching? Is it matches / total projects or matches / total consumption traces? (probably both are useful)
- Why do matching of gas monthly data?

Suggestions:
- Counts of invalid rows (break down by type of error)

**Comment by houghb** [comment]
Marc, these are great questions that we'd also like to get answers to.  I'll chime in with some of our assumptions regarding a few of the ambiguities you mention while we wait for more clarification:
- missing hour: an hour for which there is no reported usage data (including the 3AM hour on 23-hour DST days)
- estimated hours: the APCT column indicates how many hours were estimated for a given day. For the 60 minute interval data, we calculate the number of missing hours as `24 - (APCT/100)*24`
- net metering flag: in the electric cross reference table there is a `net_mtr_ind` column that indicates whether an entry is net metered.  We also considered any SAID that had any values of 'R' in the `DIR` column to be net metered (even if it was not listed as such in the cross reference table).
- combined project data: I assume this is just the [cleaned per the README] combination of the files `CalTrack (AHU) from 1_1_14__6_30_15_v2_FINAL_090816.csv`, `CalTrack (AHU) from 7_1_15__6_30_16_v2_FINAL_090816.csv`, `CalTrack (AHUP) from 1_1_14__6_30_15_v2_FINAL_090816.csv`
- "number of unique IDs in the combined project data": to get unique IDs for this table we had to add the sp_id to each project from the electric and gas cross reference tables, then merge duplicates on that `sp_id` column, so that is what we're considering a unique ID right now.

We also aren't clear on which IDs to use for many of the statistics you point out so will look forward to getting some clarification on those too.

**Comment by houghb** [comment]
@matthewgee Do you have any guidance on Marc's questions so we can incorporate the answers before the meeting tomorrow?

**Comment by matthewgee** [comment]
Great questions. Here are my thoughts and clarifications. I've modified the README to incorporate the necessary clarifications.

Hourly Elec:

"Number of unique IDs". Which one? SAID? SPID?
- SPID. We want to characterize each dataset independently first (post file-specific data cleaning procedures) before characterizing the joined files. This means using the unique identifier for a record that corresponds to that file (not the joined files). For hourly electric, that is SPID.

What id is used to define a "user"? SAID? SPID? Or do you need to use xref file?
- This was imprecise. I've changed this to "usage record" in each of the summary stat descriptors. This again should be SPID.

How do you define a "missing hour"?
- @houghb definition above is what I had in mind, with one important addition: a missing hour is an hour for which there is no reported usage, either because it is null, it had a negative value that was replaced with null, or the timestamp for that hour was missing.

How do you define an "estimated hour"?
- See @houghb definition above.

Where is the "net metering flag"?
- See above. This is correct. 

Daily gas:

Is a "user" defined by SPID? Or something else?
- Similar to the above definition, SPID. Changed to usage record.

Date integration file

What is "combined project data"?
- See @houghb. This is correct.

What ID for "number of unique IDs in combined project data"? There are a few ID columns
- SAID

Why is monthly gas data here? Isn't it being ignored?
- deleted

What ID for hourly elec data?
- the join should be sa_id to sp_id

What ID column in xref?
- the join should be sa_id to sp_id

How do you define percentage matching? Is it matches / total projects or matches / total 
- # of matches / total projects with valid (non-missing) [sa_id, sp_id] pairings.

consumption traces? (probably both are useful)
- not sure what this question means

Why do matching of gas monthly data?
- deleted

Suggestions:

Counts of invalid rows (break down by type of error)
- added

**Comment by marcrecurve** [comment]
Great, that gets pretty close. Still a few loose ends:

I think the answer to this one assumed I was asking a different question:

> What ID for hourly elec data?

This referred to the following items in the Data Integration File section:
- Number of unique IDs in hourly electricity data
- Number of unique IDs in monthly electricity data
- Number of unique IDs in the electricity cross reference dataset
- Number of unique IDS in the Gas cross reference dataset

I think that perhaps the answer to this might be to remove these items from the Data Integration File section because they are redundant.

---

This is interesting:

> number of matches / total projects with valid (non-missing) [sa_id, sp_id] pairings.

because there are actually some projects in the project files that don't have corresponding xref entries.

Might be valuable to break down these counts, e.g.
- Total projects
- Total projects without xrefs
- Total projects that match energy traces

---

Percentage matching of consumption traces:

Another way to do percentage matching is to compare the total number of consumption traces to the number that have matching projects. This would let you know how much extra consumption data you got (or, perhaps, alert you that the project file is incomplete)

So far, I've seen both extra consumption traces and extra projects in the dataset, which may indicate there are some data exporting issues upstream.

**Comment by houghb** [comment]
@marcpareoee, for your last two points:
- we removed projects that don't have corresponding xref entries (because we can't associate them with an SPID)
- we also removed any usage data ("consumption traces" in your comment) that doesn't have matching projects because we don't have any location (zip code) information for that usage data.

**Comment by matthewgee** [comment]
Some additional clarifications based on questions from @marcpare: 
- Overall impressions:
  - Whose job is it to review the summary stats? Then who leads getting them to agree?

We are reviewing the stats on the combined working group call tomorrow. I'll have to lead reconciliation if we end of with problems, but issue diagnosis will probably be done jointly over slack.

```
- Are we trying to get all the summary stats to agree?
```

Yes. We have to be sure that we are working with the same cleaned and prepped datasets before proceeding to analysis.

```
- What's the target date for this?
```

Tomorrow we review summary stats. If we agree, 
- Project Summary Stats
  - "Total number of records" sounds better than "Number of total records"

Sure. Changed.

```
- Count of projects:
  - Hugh's throwing out thing seems technically wrong given the CalTrack technical specification ("Projects that are unmatched to usage data will be listed in CalTRACK for data integrity reporting, but will not be included in any estimation procedures and will not have estimated savings"). Could you clarify?
```

As long as the lack of match gets reported in the summary statistics of unique SAIDs and SPIDs for the gas and electric cross reference files and combined data summary file match statistics (not thrown out before attempting to join so they aren't included in those unique ID counts) then it is meeting the data integrity reporting requirements. @houghb, do projects that do not have SAID-SPID pairs get included in your Unique ID counts and match rates?

```
- "Number of unique project SAIDs"
  - Both "Electric Service ID" and "Gas Service ID" in project file are SAIDs. How do you do this count? 
```

Number of unique electricity SAIDs

```
- How do you emit the "top 10 zip codes by count" in the CSV file? 10 rows? What do you name them?
```

A python list.

```
- How do you format dates in the output CSV? 

YYYY-MM-DD

  - When you average a date, you get a millisecond timestamp. Round it? Truncate? (Truncate probably the most convenient)
```

Truncate to day.

```
- There are more than 10 zip codes with a single occurence. Which ones are the "bottom 10"?
```

Bottom 10 of sorted list of zipcodes where sort order is decending [count,zip] so the smallest numeric zips are in the bottom 10.

```
- Are the Work Start/End date stats AFTER applying rules for filling in missing cells?
```

Stats are all generated on cleaned data, so yes, AFTER.

```
  - Should make it clear in the spec which stats are before project file munging and after
```

This sentence describes the four summary files that need to be generated. If I add the _emphasis_ is that clearer, or do I need to put this someplace else to make sure the ordering is clear? "There will be four _cleaned_ data reports generated by each beta tester"

**Comment by marcrecurve** [comment]
I took all of the input I got today for project summary stats and baked them into the following proposed additions to the spec:

https://github.com/impactlab/caltrack-betatest/pull/14/files

There might be some disagreement about some of the proposal, so do have a look.

**Comment by houghb** [comment]
@matthewgee 

> @houghb, do projects that do not have SAID-SPID pairs get included in your Unique ID counts and match rates?

These projects are not included in our unique ID counts because I did the counts on the cleaned usage and project tables.  We removed 444 Electric Service IDs (SAIDs) from the projects table because there wasn't a matching entry (with SPID) in the cross reference table.

**Comment by houghb** [comment]
@mcgeeyoung @matthewgee OK to close this issue?

**Comment by mcgeeyoung** [comment]
Yes, I think so. These issues have been well vetted.
