### ISSUE TITLE
Suggested changes to monthly/daily analysis, based on UMP chapter 8.

### ISSUE THREAD

**Issue by jbackusm** [impactlab/caltrack-betatest#22]
There are a few recommendations from UMP chapter 8, Section 4.6.1.2.3, that are not currently specified in our requirements:
- "Note that the cooling degree-day base must always be higher than the heating
  degree-day base."
- "Models with negative parameter estimates should be removed from consideration, although they rarely survive the optimal model selection process."

Also, the F-test or VIF we propose as part of our model-selection criteria goes beyond the suggestions in the UMP chapter 8 (see section 4.6.1.3). UMP does not explicitly mention the potential issue of multicollinearity, so is there a strong reason for us to add complexity here?

Finally, as we started to discuss on the last call, I think the criteria for falling back to default balance points (R-squared < 0.05) is not particularly well motivated. It doesn't directly address the issue of extreme balance points, though the UMP also doesn't appear to have specific suggestions as to how to address this. If only to simplify our requirements, I might suggest removing this criteria.

**Comment by matthewgee** [comment]
Agreed on the addition of hard constrains. I think we should go ahead and properly formulation of the first stage model should actually be a `max(0,tau_c)`-type model with hard inequality constrains encoded. 

Not a strong reason for adding complexity, and if we can keep it simple we should, it's just that the literature on load prediction has largely moved toward VIF implementations, so I thought we should at least consider it. But in general, simpler and more standard is better with CalTrack, so let's K.I.S.S. it.

Let's discuss the default balance point issue on today's call.

**Comment by houghb** [comment]
@matthewgee Can we make some decisions on the "hard constraints" you mentioned and other changes to the readme?  We'd like these before moving forward with generating sprint 3 summary files.  
-  "Note that the cooling degree-day base must always be higher than the heating degree-day base."
-  "Models with negative parameter estimates should be removed from consideration, although they rarely survive the optimal model selection process."
-  are we using the model selection criteria in the current README (with the F-testing, etc), or something more in line with what is in the UMP?  If we're going to go with what is currently in the README then I have another set of implementation questions, but I'll wait on those in case we are changing.

**Comment by matthewgee** [comment]
Sorry for the delay in getting to this. Let's go ahead and add:

T(HDD)<T(CDD)

B(HDD),B(CDD)>0

And let's just strictly implement UMP 8 on model selection: 
If the heating and cooling coefficients in the HC model have p-values less than
10%, retain both.
• Otherwise:
o If either the heating coefficient in the HO model or the cooling coefficient in
the CO model has a p-value of less than 10%, retain the term (heating or
cooling) with the lower p-value.
o If neither the heating nor the cooling coefficient has a p-value of less than
10% in the respective model, drop both terms and use mean consumption.
o For sites with no weather-correlated load or with a highly variable load, the
mean usage-per-day may be the most appropriate basis for estimating normal
annual consumption

**Comment by matthewgee** [comment]
Rearranging the selection criteria:
1. Parameter Search Criteria
- Search range for HDD base: `55 degrees F to 65 degrees F`
- Search range for CDD base: `65 degrees F to 75 degrees F`
- T(HDD)<=T(CDD)
1. Model Qualification Criteria
   - Parameter constraint: B(HDD),B(CDD)>0
   - If the heating and cooling coefficients in the HC model have p-values less than 10%, retain both.
2. Otherwise:
3. If either the heating coefficient in the H-only model or the cooling coefficient in
   the C-only model has a p-value of less than 10%, retain the term (heating or
   cooling) with the lower p-value.
4. If neither the heating nor the cooling coefficient has a p-value of less than
   10% in the respective model, drop both terms and use mean consumption.
5. For sites with no weather-correlated load or with a highly variable load, the
   mean usage-per-day may be the most appropriate basis for estimating normal
   annual consumption
6. Model Selection Criteria
7. Max Adj R^2
