### ISSUE TITLE
Some projects have zip codes that are not in the zip code to weather station map

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#25]
There are some zip codes in our cleaned project files `['95675', '94692', '95474', '95426', '95225', '95686', '93737']` that are not included in `ZipCodetoCZ2010WeatherStationMap_unique.csv`, so we can't associate them with weather data.

**Comment by matthewgee** [comment]
DNV is going to check internally to see if they have a complete one-to-one mapping from the CEC.

**Comment by houghb** [comment]
Just want to note that if we can't easily find a weather station mapping for those zip codes, there are only 7 projects (one for each zip code in my comment above) that this is a problem for, so the path of least resistance may be to just drop those projects...

**Comment by matthewgee** [comment]
Since we haven't heard back on the location of the mysterious complete weather station mapping file, let's drop the projects from the Beta Test analysis.

**Comment by jfarland** [comment]
The mapping that I was thinking about when I made that comment last week appears to be dated. However, we do have an algorithm that maps various geographical elements to NOAA weather stations. If I can provide the mapping quickly by zip code or lat/long, I will do so. Otherwise I agree we should drop the projects.

**Comment by jfarland** [comment]
I've mapped the seven zip codes to USAFs based on Lat/Lon. Two are still missing because the zip code database I used was last updated in 2012. I'll work on the last two over the weekend.

See attached.

[RemainingMapping.txt](https://github.com/impactlab/caltrack-betatest/files/545437/RemainingMapping.txt)

**Comment by houghb** [comment]
From slack discussion regarding the remaining two zip codes: 

"I wasn't able to match them because I wasn't able to find reliable lat/long for the zip codes (surprisingly) if anybody else can find such information, I'll match them to stations, but I say we drop the other two for now.
And close the issue"

So we will drop zip codes 94692 and 95474 from the analysis.
