### ISSUE TITLE
What to do with net metering?

### ISSUE THREAD

**Issue by jbackusm** [impactlab/caltrack-betatest#4]
The requirements doc only specifies that we will flag usages to indicate the presence of net metering, but what will we do with those flags? Will we still attempt to model the usage and obtain savings estimates, or will we exclude them from direct analysis?

For the sake of avoiding too much complexity in the beta test, I would suggest we exclude net-metered usage (and associated accounts) from the analysis. Otherwise, I think we will need to discuss how best to model net-metered usage.

Actually, first, can we confirm that the hourly usage data is in fact the _net_ usage, not the gross usage, for the SAID's flagged with "net_mtr_ind" == "Y" in the x-ref table?

**Comment by jfarland** [comment]
@jbackusm @matthewgee 

My preference has always been to simply drop the received energy (e.g., solar) to get things going at the beginning of the analysis. I don't drop the site altogether, however. I suggest that we continue to model the "delivered" energy for these sites, for now, and make a difference between sites with net metering and without in subsequent analysis (e.g., Stage Two of the Two Stage Models)

The hourly usage data has observations with both "D" and "R" flagged in the DIR field. I haven't checked, admittedly, but I would expect any site that has observations with both "D" and "R" in the hourly data also has a "net_mtr_ind" == "Y" in the x-ref table. Net energy would be the difference between the "D" and "R", I believe. So there's some flexibility there.

**Comment by jbackusm** [comment]
Thanks for the clarification @jfarland. So the "delivered" usage data is the gross usage at that meter? If so, I agree with your suggestion.

At first glance, it looks like your assumption is right, though there may be a small but significant number of cases where 'DIR' == 'R' but 'net_mtr_ind' == 'N'.

**Comment by jfarland** [comment]
Well, it looks like it's not as simple as I thought. I was under the impression that this had changed, but it looks like data collection for PG&E meters with net metering work a little differently than I had inferred. 

Net Metering sites are still an issue for our modeling purposes here because, even though PG&E tracks what quantity of energy was both received and delivered to a customer, both of those components don't necessarily quantify how much total electricity that home was using at any given time. So if the household used 4 kw in a given hour, the utility provided 3 kw and a solar system produced 1 kw, the value for DIR("R") -> 0, and DIR("D") -> 3. There's no way to get to 4, with 3 and 0.

I'm actually in a room with some PG&E staff now , and they have confirmed this to be the case.

_"Delivered" is not the gross usage at the site as I had thought_

Do we know how many sites are net metered? I think it's best to set these sites aside for now to build out the rest of the modeling pipeline first.

**Comment by jbackusm** [comment]
Ok, good to know. I agree that we should probably set these sites aside for now.

**Comment by houghb** [comment]
Resolved
