### ISSUE TITLE
Create one-to-one weather station mapping file using proximity to zip code centroid

### ISSUE THREAD

**Issue by matthewgee** [impactlab/caltrack-betatest#8]

**Comment by houghb** [comment]
@matthewgee Any update on getting this mapping?

**Comment by houghb** [comment]
@matthewgee The updated weather station mapping (*_unique.csv) still has duplicate weather stations for the same zip code.  For example see 90007, 90015, 90016, 90018...

**Comment by houghb** [comment]
@mcgeeyoung We still don't have a 1:1 weather station mapping, so the weather station files in the repo don't work without further modification.  This seems like something to fix before releasing V1.0.  OEE said they would correct this mapping back in September, any progress?

**Comment by mcgeeyoung** [comment]
@houghb Are the files provided by DNV not doing the trick?

**Comment by houghb** [comment]
Good call, it looks like that file is deduplicated (assuming the file provided by DNV is called `stationmapping_v2.csv`).  Since this issue hadn't been closed I kept the deduplication step in our code, but it isn't doing anything since there are no longer any duplicates.

I am going to close this issue, though I don' t know for sure that the deduplicated file actually uses proximity to the zip code centroid as suggested in the issue title; I suspect it might just be a file with the first or last duplicate retained (which works for our purposes).
